prd:
  catalog_name: mlops_prd
  schema_name: jenspete
acc:
  catalog_name: mlops_acc
  schema_name: jenspete
dev:
  catalog_name: mlops_dev
  schema_name: jenspete


num_features:
  - total_items
  - subtotal
  - num_distinct_items
  - min_item_price
  - max_item_price
  - total_onshift_dashers
  - total_busy_dashers
  - total_outstanding_orders
  - estimated_order_place_duration
  - estimated_store_to_consumer_driving_duration


time_features:
  - created_at
  - actual_delivery_time

cat_features:
  - market_id
  - store_id
  - store_primary_category
  - order_protocol


target: SalePrice
