prd:
  catalog_name: mlops_prd
  schema_name: jenspete
acc:
  catalog_name: mlops_acc
  schema_name: jenspete
dev:
  catalog_name: mlops_dev
  schema_name: jenspete

experiment_name_basic: /Shared/doordash-eta-basic
experiment_name_custom: /Shared/doordash-eta-custom

parameters:
  iterations: 1000

num_features:
  - total_items
  - subtotal
  - num_distinct_items
  - min_item_price
  - max_item_price
  - total_onshift_dashers
  - total_busy_dashers
  - total_outstanding_orders
  - estimated_order_place_duration
  - estimated_store_to_consumer_driving_duration


time_features:
  - created_at

cat_features:
  - market_id
  - store_id
  - store_primary_category
  - order_protocol


target: leadtime_in_s
